"use server"

import { db } from "@/lib/db";
import { auth } from "@/lib/auth";
import { generateObject } from "ai";
import { openai } from "@ai-sdk/openai";
import { retrieveContext } from "@/lib/rag";
import { z } from "zod";

// --- 1. SCHEME OF WORK ---

const SchemeOfWorkSchema = z.object({
  title: z.string(),
  termlyOverview: z.object({
    totalLessons: z.number(),
    strandsCovered: z.array(z.string()),
    communityServiceActivities: z.array(z.string()),
    parentalEngagementStrategies: z.array(z.string()),
    crossCurricularIntegration: z.array(z.string())
  }),
  weeks: z.array(z.object({
    weekNumber: z.number(),
    lessons: z.array(z.object({
      lessonNumber: z.number(),
      strand: z.string(),
      subStrand: z.string(),
      specificLearningOutcomes: z.array(z.string()),
      keyInquiryQuestions: z.array(z.string()),
      learningExperiences: z.array(z.string()),
      learningResources: z.array(z.string()),
      assessmentMethods: z.array(z.string()),
      coreCompetencies: z.array(z.string()),
      reflection: z.string().optional()
    }))
  }))
});

export async function generateSchemeOfWork(curriculumId: string | undefined | null, parameters: { grade: string, subject: string, term: string, weeks: number, holidays: number, lessonsPerWeek: number, durationMinutes: number }) {
  const { userId } = await auth();
  if (!userId) throw new Error("Unauthorized");

  // Pre-verification: ZERO-WASTE CHECK
  const docExists = await db.curriculumDocument.findFirst({
    where: { gradeLevel: parameters.grade, subject: parameters.subject }
  });
  if (!docExists) {
    throw new Error(`MISSING CURRICULUM: No KICD Design uploaded for ${parameters.grade} ${parameters.subject}. To prevent AI hallucinations and token waste, please ask your Administrator to upload the PDF first.`);
  }

  // GLOBAL CACHE SHARING: Zero-Token Optimization
  const cachedScheme = await db.schemeOfWork.findFirst({
    where: { grade: parameters.grade, subject: parameters.subject, term: parameters.term }
  });

  if (cachedScheme) {
    return cachedScheme; // Return existing scheme generated by another teacher instantly!
  }

  const query = `Curriculum for ${parameters.grade} ${parameters.subject} Term ${parameters.term}`;
  const contextChunks = await retrieveContext(query, 10, { grade: parameters.grade, subject: parameters.subject });
  const contextText = contextChunks.map(c => c.chunkText).join("\n\n");

  // Fetch Custom Guidelines from DB
  const customRule = await db.generationRule.findUnique({ where: { contentType: "SCHEME_OF_WORK" } });
  const customRuleText = customRule?.customPrompt ? `\n\nCUSTOM PLATFORM GUIDELINES (STRICTLY ENFORCE):\n${customRule.customPrompt}\n` : "";

  const systemPrompt = `You are an expert KICD curriculum specialist. Generate a Scheme of Work strictly following the Competency-Based Curriculum (CBC) architecture rules.${customRuleText}

INPUT DATA:
- Grade Level: ${parameters.grade}
- Subject: ${parameters.subject}
- Term: ${parameters.term}
- Duration: ${parameters.durationMinutes} minutes

MANDATORY REQUIREMENTS:
1. Extract ALL strands and sub-strands from the provided curriculum context below.
2. Extract EXACT learning outcomes (do not paraphrase).
3. Calculate total available lessons: (${parameters.weeks} weeks - ${parameters.holidays} holidays) × ${parameters.lessonsPerWeek} lessons per week.
4. Distribute lessons proportionally across strands ensuring weekly progression from simple to complex.
5. Include all 7 CBC core competencies across activities.
6. Add at least 2 Community Service Learning activities and 2 Parental Engagement strategies.
7. Use diverse assessment methods (e.g., observation, oral, practical).
8. Use age-appropriate language for Grade ${parameters.grade}.

CURRICULUM CONTEXT:
${contextText}
`;

  const { object } = await generateObject({
    model: openai("gpt-4o"),
    schema: SchemeOfWorkSchema,
    system: systemPrompt,
    prompt: `Generate the complete Scheme of Work now mapped exactly to the detailed Zod schema format.`,
  });

  const scheme = await db.schemeOfWork.create({
    data: {
      title: object.title,
      grade: parameters.grade,
      subject: parameters.subject,
      term: parameters.term,
      content: object as any,
      teacherId: userId,
      curriculumId: curriculumId ?? null
    }
  });

  return scheme;
}


// --- 2. LESSON PLAN ---

const LessonPlanSchema = z.object({
  topic: z.string(),
  strand: z.string(),
  subStrand: z.string(),
  specificLearningOutcomes: z.array(z.string()),
  keyInquiryQuestions: z.array(z.string()),
  learningResources: z.array(z.string()),
  coreCompetencies: z.array(z.object({
    competency: z.string(),
    howDeveloped: z.string()
  })),
  values: z.array(z.object({
    value: z.string(),
    howDemonstrated: z.string()
  })),
  lessonStructure: z.object({
    introduction: z.object({
      duration: z.number(),
      recap: z.string(),
      connectionToLearnersLives: z.string(),
      learningIntentions: z.string(),
      successCriteria: z.string()
    }),
    mainActivities: z.array(z.object({
      activityName: z.string(),
      duration: z.number(),
      grouping: z.string(),
      teacherActions: z.array(z.string()),
      learnerActions: z.array(z.string()),
      formativeAssessment: z.string()
    })),
    differentiation: z.object({
      learnersNeedingSupport: z.string(),
      averageLearners: z.string(),
      advancedLearners: z.string()
    }),
    conclusion: z.object({
      duration: z.number(),
      summary: z.string(),
      assessmentOfLearning: z.string(),
      exitTicket: z.string(),
      previewNextLesson: z.string(),
      homework: z.string()
    })
  }),
  assessmentRubric: z.object({
    criteria: z.string(),
    exceeding: z.string(),
    meeting: z.string(),
    approaching: z.string(),
    below: z.string()
  })
});

export async function generateLessonPlan(schemeId: string, lessonNumber: number, topic: string) {
  const { userId } = await auth();
  if (!userId) throw new Error("Unauthorized");

  const scheme = await db.schemeOfWork.findUnique({ where: { id: schemeId } });
  if (!scheme) throw new Error("Scheme not found");

  const customRule = await db.generationRule.findUnique({ where: { contentType: "LESSON_PLAN" } });
  const customRuleText = customRule?.customPrompt ? `\n\nCUSTOM PLATFORM GUIDELINES (STRICTLY ENFORCE):\n${customRule.customPrompt}\n` : "";

  const systemPrompt = `You are an expert KICD-trained teacher. Generate a highly detailed Lesson Plan conforming to strict CBC architecture.${customRuleText}

MANDATORY REQUIREMENTS:
1. Follow the 3-part lesson structure. Time breakdown: 10-15% Introduction, 70-80% Main Activity, 10-15% Conclusion.
2. Expand scheme activities into step-by-step detailed activities specifying teacher/learner actions and specific dialogue ("Teacher says: xxx").
3. Specify groupings (whole class/pairs/individual).
4. Include differentiation strategies for 3 levels: Learners Needing Support (concrete examples/scaffolding), Average Learners (standard activity), Advanced Learners (extension/higher-order thinking).
5. Create a 4-level CBC assessment rubric with specific observable behaviors (Exceeding, Meeting, Approaching, Below).
6. Tag core competencies and values, detailing precisely how they are developed during the lesson.

SCHEME CONTENT TO EXTRACT FROM:
${JSON.stringify(scheme.content)}
`;

  const { object } = await generateObject({
    model: openai("gpt-4o"),
    schema: LessonPlanSchema,
    system: systemPrompt,
    prompt: `Generate the full expanded Lesson Plan for Lesson ${lessonNumber}: "${topic}". Ensure output respects the heavy Zod schema.`,
  });

  const lessonPlan = await db.lessonPlan.create({
    data: {
      lessonNumber,
      topic: object.topic,
      objectives: object.specificLearningOutcomes,
      content: object as any,
      schemeId,
      teacherId: userId
    }
  });

  return lessonPlan;
}


// --- 3. LESSON NOTES ---

const LessonNoteSchema = z.object({
  conceptOverview: z.object({
    whatLearnersNeedToKnow: z.string(),
    whyThisIsImportant: z.string(),
    prerequisites: z.string()
  }),
  detailedTeachingSequence: z.array(z.object({
    step: z.string(),
    conceptExplanation: z.string(),
    workedExamples: z.array(z.object({
      difficulty: z.string(),
      problem: z.string(),
      solution: z.string()
    })),
    questioningSequence: z.array(z.object({
      initialQuestion: z.string(),
      expectedAnswer: z.string(),
      ifCorrect: z.string(),
      ifIncorrect: z.string(),
      followUp: z.string(),
      challengeQuestion: z.string().optional()
    }))
  })),
  commonMisconceptions: z.array(z.object({
    misconception: z.string(),
    correction: z.string(),
    practice: z.string()
  })),
  differentiationMaterials: z.object({
    forSupport: z.object({
      strategy: z.string(),
      worksheetOutline: z.string()
    }),
    forAverage: z.object({
      worksheetOutline: z.string()
    }),
    forAdvanced: z.object({
      extensionTasks: z.string(),
      challengeWorksheetOutline: z.string()
    })
  }),
  markingGuide: z.object({
    taskDescription: z.string(),
    pointAllocation: z.array(z.object({
      component: z.string(),
      marks: z.number(),
      whatToLookFor: z.string()
    }))
  }),
  interventionStrategies: z.array(z.object({
    strategy: z.string(),
    example: z.string()
  }))
});

export async function generateLessonNotes(lessonPlanId: string) {
  const { userId } = await auth();
  if (!userId) throw new Error("Unauthorized");

  const lessonPlan = await db.lessonPlan.findUnique({ where: { id: lessonPlanId } });
  if (!lessonPlan) throw new Error("Lesson Plan not found");

  const customRule = await db.generationRule.findUnique({ where: { contentType: "LESSON_NOTES" } });
  const customRuleText = customRule?.customPrompt ? `\n\nCUSTOM PLATFORM GUIDELINES (STRICTLY ENFORCE):\n${customRule.customPrompt}\n` : "";

  const systemPrompt = `You are an experienced Kenyan educator crafting granular Lesson Notes for classroom delivery.
The Lesson Notes are the TEACHER'S DETAILED GUIDE for delivering the lesson plan.${customRuleText}

MANDATORY REQUIREMENTS:
1. Expand EVERY single activity from the lesson plan into rich step-by-step procedures.
2. Embed 3 Worked Examples (Basic, Medium, Advanced) containing specific think-aloud commentary.
3. Write deep Questioning Sequences showing the initial question, expected answer, positive reinforcement, wrong-answer handling, and challenge follow-ups.
4. Curate an exhaustive list of Common Misconceptions, providing instructions on how to correct them.
5. Fabricate actual materials content (Worksheet outlines) tailored to differentiation strategies (Support/Average/Advanced).
6. Provide a Marking Guide with clear point allocations.

SOURCE LESSON PLAN DATA:
${JSON.stringify(lessonPlan.content)}
`;

  const { object } = await generateObject({
    model: openai("gpt-4-turbo"),
    schema: LessonNoteSchema,
    system: systemPrompt,
    prompt: `Produce the Teacher Lesson Notes aligned completely with the Zod schema provided.`,
  });

  const notes = await db.lessonNote.create({
    data: {
      lessonPlanId,
      notes: object.conceptOverview.whatLearnersNeedToKnow,
      resources: object as any,
      teacherId: userId
    }
  });

  return notes;
}

// --- 4. ASSESSMENTS ---

const AssessmentSchema = z.object({
  title: z.string(),
  assessmentType: z.string(),
  totalMarks: z.number(),
  durationMinutes: z.number(),
  instructions: z.array(z.string()),
  sections: z.array(z.object({
    sectionName: z.string(),
    instructions: z.string(),
    totalMarks: z.number(),
    questions: z.array(z.object({
      questionNumber: z.number(),
      questionText: z.string(),
      marks: z.number(),
      questionType: z.string(),
      bloomsLevel: z.string(),
      learningOutcomeTested: z.string()
    }))
  })),
  markingScheme: z.array(z.object({
    questionNumber: z.number(),
    expectedAnswers: z.array(z.string()),
    pointAllocation: z.array(z.object({
      component: z.string(),
      marks: z.number()
    })),
    alternativeMethods: z.string().optional(),
    partialCreditCriteria: z.string().optional()
  })),
  rubric: z.object({
    criteria: z.array(z.object({
      name: z.string(),
      exceeding: z.string(),
      meeting: z.string(),
      approaching: z.string(),
      below: z.string()
    }))
  }).optional()
});

export async function generateAssessment(parameters: { grade: string, subject: string, term: string, type: string, totalMarks: number, durationMinutes: number }) {
  const { userId } = await auth();
  if (!userId) throw new Error("Unauthorized");

  // Pre-verification: ZERO-WASTE CHECK
  const docExists = await db.curriculumDocument.findFirst({
    where: { gradeLevel: parameters.grade, subject: parameters.subject }
  });
  if (!docExists) {
    throw new Error(`MISSING CURRICULUM: No KICD Design uploaded for ${parameters.grade} ${parameters.subject}. To prevent AI hallucinations and token waste, please ask your Administrator to upload the PDF first.`);
  }

  // GLOBAL CACHE SHARING: Zero-Token Optimization
  // If an exact exam of this type already exists globally, return it instantly!
  const cachedAssessment = await db.assessment.findFirst({
    where: { grade: parameters.grade, subject: parameters.subject, type: parameters.type }
  });

  if (cachedAssessment) {
    return cachedAssessment;
  }

  const query = `Curriculum for ${parameters.grade} ${parameters.subject} Term ${parameters.term}`;
  const contextChunks = await retrieveContext(query, 12, { grade: parameters.grade, subject: parameters.subject });
  const contextText = contextChunks.map(c => c.chunkText).join("\n\n");

  const customRule = await db.generationRule.findUnique({ where: { contentType: "ASSESSMENT" } });
  const customRuleText = customRule?.customPrompt ? `\n\nCUSTOM PLATFORM GUIDELINES (STRICTLY ENFORCE):\n${customRule.customPrompt}\n` : "";

  const systemPrompt = `You are an expert assessment designer following KICD CBC guidelines.
Generate a formal Assessment Paper and marking scheme.${customRuleText}

INPUT DATA:
- Grade Level: ${parameters.grade}
- Subject: ${parameters.subject}
- Assessment Type: ${parameters.type}
- Total Marks: ${parameters.totalMarks}
- Duration: ${parameters.durationMinutes} minutes

MANDATORY REQUIREMENTS:
1. Generate questions covering ALL specified learning outcomes from the curriculum context.
2. Follow Bloom's taxonomy distribution closely for Grade ${parameters.grade}. If Lower Primary, rely heavily on Remember/Understand/Apply (40/35/20%). If Upper Primary, balance Remember/Understand/Apply/Analyze (25/30/25/15%). If Junior Secondary, spread across all levels including Evaluate/Create.
3. Distribute marks proportionally across strands. Ensure difficulty progression (easy -> hard).
4. Provide a Detailed Marking Scheme allocating specific points for every question, acknowledging alternative answers and partial credit.
5. Provide a 4-level CBC rubric (Exceeding, Meeting, Approaching, Below) for project/performance tasks if applicable.
6. Use age-appropriate language and culturally relevant Kenyan contexts.
7. Use clear directive verbs (List, Explain, Calculate, Draw).

CURRICULUM CONTEXT:
${contextText}
`;

  const { object } = await generateObject({
    model: openai("gpt-4o"),
    schema: AssessmentSchema,
    system: systemPrompt,
    prompt: `Generate the complete assessment paper with marking scheme now.`,
  });

  const assessment = await db.assessment.create({
    data: {
      title: object.title,
      grade: parameters.grade,
      subject: parameters.subject,
      type: parameters.type,
      content: object as any,
      teacherId: userId
    }
  });

  return assessment;
}
